[package]
name = "bevy_manifest"
version = "0.8.0"
edition = "2021"
description = "BevyManifest utilities"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
toml = "0.5.8"
syn = "1.0"
